### PR TITLE
Usability improvements, updated man page.

### PR DESCRIPTION
**Pull request by hackerb9**
Fix up man page, avoid reading stdin if it's a tty, add convenience
options (-T, -c), and change man page & help message to suggest github
instead of e-mailing Åstrand.

### CODE REVIEW

**Comment by hackerb9** [comment]
Here's the updated man file so you can see what's changed. [xclip.pdf](https://github.com/astrand/xclip/files/3695678/xclip.pdf)

(PS: I tried attaching the PDF using xclip, but ^V pasted in raw binary as text.)

**Comment by astrand** [comment]
Thanks. Would it be possible that you split this work into multiple parts? Ie: One part that improves the documentation for the existing implementation, and one or more part that adds new functionality?

**Comment by hackerb9** [comment]
That makes a lot of sense, but I improved the man page as I was documenting the changes I made. 

Before we consider the documentation, would you please consider first the two changes I made to xclip.c (stdin and shortcuts)? If those are acceptable, then I won't have to go to extra work to try to remove documenting them from my updated man page.

**Comment by astrand** [comment]
I'd like these changes to be separated into two pull requests. If they touch the same lines (or close), one of the pull requests can build upon the other.

For the moment, not many changes are done to xclip, so in general I'd like feedback from the community before accepting changes. This means that merging can take some time.

**Comment by hackerb9** [comment]
I'll see what I can do.

**Comment by hackerb9** [comment]
Closing as I have split this pull request into three new ones.

**Comment by hackerb9** [comment]
Hi! As requested, I split this into separate pull requests, but I have yet to hear any feedback from the community. Is there something I can do to help move this forward? Thanks!

**Comment by hackerb9** [comment]
Hello again,

I know you said it may take some time and I don't mean to be a bother. It's been over a month and there doesn't appear to be any community feedback, positive or negative. As you may have noticed my patches are fairly straightforward. They are easy to understand, so one can readily see if they have detrimental side-effects or not (I don't believe they do). 

What more can I do to help move the discussion forward?

Thanks!

**Comment by astrand** [comment]
I am very sorry, but unfortunately I have no time. Right now, it's not much that I can do: Since xclip is included in many distributions etc, I want to maintain stability. This means that I cannot accept pull requests without looking at them and testing that they work , and right now, I have no time for this. Another possibility could be peer review and testing from somebody else, but just accepting pull requests without a review is not a good idea.

It's still on my TODO list to look at all issues and pull requests though, but it will probably take some.

**Comment by hackerb9** [comment]
Re-closing as merge requestcloses #88 covers all of these improvements plus more.

**Pull request closed without merging**
